font:
  - file: "gfonts://Roboto"
    id: font_temp_md
    size: 20
    glyphs:
      - "0123456789.-°C"

  - file: "gfonts://Roboto"
    id: font_temp_lg
    size: 30
    glyphs:
      - "0123456789.-°C"