image:
  - file: "boiler-temperature/images/screen_bg_320x240.png"
    id: screen_bg
    type: RGB565

output:
  - platform: ledc
    pin: GPIO10
    id: backlight_pwm
    frequency: 1000 Hz

light:
  - platform: monochromatic
    name: "Display Backlight"
    output: backlight_pwm
    restore_mode: ALWAYS_OFF
    default_transition_length: 1s
    id: display_backlight

spi:
  clk_pin: GPIO6
  mosi_pin: GPIO7

display:
  - platform: ili9xxx
    model: ILI9341
    cs_pin: GPIO3
    dc_pin: GPIO5
    reset_pin: GPIO2
    invert_colors: false
    rotation: 270
    color_palette: 8BIT
    update_interval: 5s
    id: tft_display
    lambda: |-
      const Color white(230, 246, 242);
      const Color red(255, 82, 67);
      const Color blue(0, 160, 255);
      const Color cyan(29, 225, 216);

      auto print_temp = [&](int x, int y, auto *font, Color color, float value) {
        if (std::isnan(value)) {
          it.printf(x, y, font, color, TextAlign::TOP_CENTER, "--.-°C");
        } else {
          it.printf(x, y, font, color, TextAlign::TOP_CENTER, "%.1f°C", value);
        }
      };

      it.image(0, 0, id(screen_bg));
      print_temp(125, 24, id(font_temp_lg), white, id(pogoda_temperatura).state);
      print_temp(45, 160, id(font_temp_md), red, id(kotel_podacha).state);
      print_temp(132, 160, id(font_temp_md), blue, id(kotel_obratka).state);
      print_temp(245, 96, id(font_temp_lg), cyan, id(boiler_temperatura).state);